# 30 Cheat Codes to Beat Every Level of Life

**Summary**: ## Summary
Daniel Pink delivers 30 compressed operating principles organised into five levels — decisions, people, productivity, work, and life — drawn from six decades, seven books, and what he calls "conservatively, 10,000 mistakes." The through-line is that most life improvement comes from lowering friction and choosing better defaults rather than from willpower or heroic effort: decide by ordinary Tuesdays, make first steps embarrassingly small, build infrastructure for friendship, and learn which suffering to remove versus accept. For anyone who wants a dense checklist of decision and productivity heuristics rather than a single framework.

## Key Points
- **The numbering is wrong in Level 5** [12:55] — After code 25 he announces **"Number 29"** for the spend-money-on-recurring-misery code, then continues 27, 28, **29 again** [14:06], 30. So **26 is never spoken and 29 is spoken twice**. The level structure (six codes per level, 25–30) makes 26 the evidently intended number for the [12:55] code. Recorded as spoken; not silently renumbered.
- **The total of 30 still holds** [00:21] — Thirty distinct codes are delivered across five levels of six each: decisions 1–6, people 7–12, productivity 13–18, work 19–24, life 25–30. Only the labels slip, not the count. Several codes are announced without the word "number" (2, 7, 15, 19, 25).
- **Pink's credentials check out** [00:14] — "Seven books about human behavior" is correct (*Free Agent Nation*, *A Whole New Mind*, *The Adventures of Johnny Bunko*, *Drive*, *To Sell Is Human*, *When*, *The Power of Regret*), as is the White House reference — he was chief speechwriter to Vice President Al Gore, 1995–97.
- **Decide by ordinary Tuesday, not fantasy Saturday** [00:52] — Don't choose a house, job or city by its best day. "What will you actually be doing on the job at 2:30 on a Tuesday afternoon?" His own test on leaving the White House: give up a few days a year of excitement, but "51 out of 52 Tuesdays would be better."
- **One-way vs two-way doors** [01:38] — "Don't spend three weeks agonizing over something you can undo in three minutes." Save deliberation for irreversible decisions.
- **Judge decisions by process, not outcome** [03:15] — "A smart decision can produce a bad result, a dumb decision can get lucky." Ask: did I use the information available, consider alternatives, understand the risks?
- **The mistake he's made more than any other** [03:52] — Before solving someone's problem, ask what they want: advice, help, or just company. "Not every problem somebody tells you about is an invitation to solve it."
- **Curiosity as a diagnostic** [04:40] — "Pay attention to who is genuinely curious about you, and pay even closer attention to who never is."
- **Friendship needs infrastructure** [05:11] — "Let's get together sometime" is "how people slowly disappear from your life." He keeps a regular gathering with six friends. Specific beats vague: "Let's have a beer Thursday at 6:00" versus "let's get together" — "One is a plan, the other is goodbye in slow motion."
- **Toxic people, relatives included** [06:01] — "Shared DNA isn't a license to treat you poorly. Distance isn't always cruel. Sometimes distance is an act of wisdom."
- **The Lorne Michaels rule — verified** [06:42] — "We don't go on because we're ready. We go on because it's 11:30." Confirmed as a genuine Michaels line about real deadlines (commonly rendered "The show doesn't go on because it's ready; it goes on because it's 11:30"). Pink's self-talk when finishing: "Dude, it's 11:30."
- **Make the first step embarrassingly small** [07:04] — "Don't write the book, write three sentences. Don't get in shape, put your shoes by the door." The size of the first step and the odds of taking it are inversely related.
- **Difficulty is not evidence of virtue** [07:23] — "Use the rotisserie chicken… That's just self-inflicted pain with a superiority complex."
- **Appointments beat willpower** [07:54] — He scheduled "clean my top dresser drawer" for 2:30 on a Wednesday and removed "roughly 47 mismatched socks." — "Willpower is usually unreliable. Appointments are usually unavoidable."
- **The waiting-for list — attribution correct** [08:33] — Credited to David Allen's *Getting Things Done*, and it is a genuine core GTD component for tracking what others owe you. "Otherwise your brain will keep trying to remember them, usually at 3:00 in the morning."
- **Busyness as warning, not status** [08:57] — "When everything feels urgent, stop adding. Subtract." Leave white space: "Not every square on the calendar needs to produce something."
- **Ask for the deadline, then the real deadline** [10:40] — "When do you need this?" and "when will somebody actually use this?" are different questions. "Fake deadlines create unnecessary work and unnecessary panic."
- **Take the undefended territory** [11:41] — Get good at something valuable everyone avoids: "Neglected skills have very little competition because everyone is fighting for the glamorous territory."
- **Recurring misery beats occasional pleasure** [12:55] — "The weekend in Antigua lasts three days. The mattress is every night of your year." (This is the mis-numbered code — announced as 29, belongs at 26.)
- **The final code: two kinds of suffering** [14:45] — "Eliminate the suffering that gets you nothing, accept the suffering that moves you closer to something meaningful." Anything worthwhile "will demand effort, discomfort, criticism, uncertainty, and sacrifice" — encountering those costs doesn't mean you're doing it wrong, "you might simply be paying the price of admission."
- **His own closing instruction** [15:32] — "Don't try all 30. Pick two. One that would remove hassle from your life, and one you've been resisting. Use both this week."

## Raw Content

**[00:00] Framing** — "Video games have cheat codes… after six decades on this planet, I've discovered that life has cheat codes, too. It's just that nobody ever hands you the list. So, I made one." Credentials: "I've written seven books about human behavior, raised three children, stayed married for three decades, and made, conservatively, 10,000 mistakes." What survived: **30 cheat codes in five levels — how to decide, how to deal with people, how to get things done, how to work, and how to live.** He flags that one "might require avoiding your relatives" and that the most important is last.

**[00:52] Level 1, Decisions — codes 1–2** — **1. Make decisions using an ordinary Tuesday, not a fantasy Saturday.** Choosing a house, job or city by its best day is the error — "that house has an amazing entertainment space you'll use four times a year. That job comes with a glamorous conference in Lisbon." Ask instead what the commute feels like on a Tuesday, what you're doing at 2:30 on a Tuesday afternoon, what cooking in that kitchen feels like on a regular Tuesday night. He used this standard leaving the White House: "Sure, I give up a few days each year of extreme excitement, but 51 out of 52 Tuesdays would be better." **2. For reversible decisions, decide fast.** "Don't spend three weeks agonizing over something you can undo in three minutes." Some decisions are one-way doors deserving time and care; most are two-way doors — "take the class, go on a date, accept a brief gig. If it doesn't work, walk back through."

**[02:06] Codes 3–4** — **3. Ask "what would change my mind?"** "If your answer is nothing, you're not thinking, you're defending." Before an important project, job or move, "find one smart person who thinks it's a terrible idea. You don't have to obey them, but you do have to hear them." **4. Before deciding what to do, ask what happens if you do nothing.** "Inaction itself is a decision, one with consequences, but some problems disappear when you stop feeding them." The inversion: "the best advice isn't don't just stand there, do something, it's don't just do something, stand there."

**[02:50] Codes 5–6** — **5. Make lots of small bets.** "Take risks whose upside could change your life and whose downside won't ruin it" — side project, submit the article, try the idea at small scale. "You don't always find the big things through one heroic leap. Sometimes you find it through a portfolio of small experiments. Most of life is shots on goal." **6. Judge decisions by how you made them, not only by how they turned out.** "A smart decision can produce a bad result, a dumb decision can get lucky." Don't let one good outcome convince you the process was brilliant or one bad outcome that it was flawed. "You don't control the universe, but you do control the decision."

**[03:52] Level 2, People — codes 7–9** — **7. Before solving someone's problem, ask what they want from you: advice, help, or just company.** He calls this "the mistake I've made more than any other." "Not every problem somebody tells you about is an invitation to solve it… before going into superhero problem-solving mode, ask." **8. Assume incompetence before malice.** "What looks like hostility is often distraction, disorganization, or somebody having a terrible day… the world contains fewer enemies and more overwhelmed people than we think. So begin with the more generous explanation. You can always revise it if the evidence changes." **9. Notice who asks you questions.** "Curiosity is an underrated diagnostic for friendship, for romance, for collaboration."

**[04:59] Codes 10–12** — **10. Don't keep score in relationships you want to keep.** "I called last time. I paid for dinner. I helped her move. He still hasn't thanked me." — "generosity stops being generosity when you maintain a spreadsheet." Strong relationships "become roughly reciprocal over time, but they aren't always equal in every moment." **11. Build an infrastructure for friendship.** Make recurring plans: "a monthly dinner, a Saturday morning walk, a standing phone call." He has a regular gathering with six good friends "where we eat, drink, and offer one another advice" — without the recurring date, "I suspect we'd see one another twice a year and spend half the evening saying, hey, we should do this more often." **12. Eliminate toxic people.** "If someone consistently diminishes you, damages you, or poisons your life, get rid of them. Unfortunately, this includes relatives."

**[06:34] Level 3, Productivity — codes 13–14** — **13. Define done before you begin.** "Otherwise, every project quietly becomes an infinite undertaking. What will finished look like? Decide that first." Near the finish, invoke Lorne Michaels, creator of *Saturday Night Live*: "We don't go on because we're ready. We go on because it's 11:30." Pink's version: "Dude, it's 11:30." **14. Make the first step embarrassingly small.** "Don't write the book, write three sentences. Don't get in shape, put your shoes by the door. Don't organize the house, clean one drawer. The size of the first step and the odds of taking it are inversely related."

**[07:23] Codes 15–16** — **15. Let it be easy.** "Difficulty is not evidence of virtue. Use the rotisserie chicken. Listen to the audiobook. Buy the pre-cut vegetables. Take the shortcut when the shortcut actually works." On the opposite instinct: "we absorbed the idea that if something isn't excruciatingly hard, it doesn't count. That's just self-inflicted pain with a superiority complex." **16. Prepare tomorrow's first move tonight.** "Make starting so easy that your morning self, who let's be honest, you cannot trust, has almost no decisions to make." Open the document, set out the running clothes, put the unpleasant task on the calendar "with a day, a time, and a place." His example: scheduled "clean my top dresser drawer" for 2:30 on a Wednesday, and at 2:30 removed "roughly 47 mismatched socks." — "Willpower is usually unreliable. Appointments are usually unavoidable."

**[08:33] Codes 17–18** — **17. Keep a waiting-for list.** Learned from David Allen's *Getting Things Done*: "We're usually pretty good at tracking what we need to do, but we're much worse at tracking what other people owe us" — the proposal under review, the document someone promised, the answer you need to move forward. "Write those things down in one place, otherwise your brain will keep trying to remember them, usually at 3:00 in the morning." **18. Treat constant busyness as a warning, not a status symbol.** "When I ask someone how are you and they answer, oh, I'm so busy, I become suspicious." Sometimes it means a full life, "but sometimes it means you're refusing to make choices, you're ignoring priorities, or you're just feeding your own ego. When everything feels urgent, stop adding. Subtract. Cancel something. Decline something." Leave white space "for a walk, a strange book, or an unexpected conversation, or just 15 minutes of staring out the window."

**[09:40] Level 4, Work — codes 19–21** — **19. Send the recap email.** After an important meeting: "Here's what we decided. Here's who is doing what. Here's when it's due." It helps everyone, but also you, "because translating a conversation into writing forces you to understand what actually happened." On tooling: "AI can help organize that note, but don't let it do all the thinking. The thinking is part of the benefit." **20. Make your boss's life easier.** "Bosses divide employees into two categories: people who make my life harder, and people who make my life easier. Especially early in your career, make sure you're in the second category… That's how you become indispensable." **21. Ask for the deadline, then ask for the real deadline.** "When do you need this, and when will somebody actually use this? Those are two very different questions. One answer might be Friday. The other might be the board meeting three Thursdays from now." And reciprocally — "you won't inflict unnecessary deadlines on other people."

**[11:12] Codes 22–24** — **22. Lead with the request and bring a recommendation.** "Don't begin an email with seven paragraphs of throat clearing." And bring a proposed solution with any problem: "Diagnosis is useful. Prescription is essential." Instead of "this isn't working," try "this isn't working. Here's what I think is causing it, and here's what I recommend we do next." **23. Get good at something valuable that everybody else avoids** — "the spreadsheet nobody wants to own, the presentation nobody wants to give, the difficult conversation everybody keeps avoiding. Neglected skills have very little competition because everyone is fighting for the glamorous territory. But the neglected territory is sitting there undefended." **24. Don't be the boss you had, be the boss you should have had.** "Remember what your worst managers did and do the opposite. Then remember what you desperately needed from them and never got — clarity, encouragement, honest feedback, or a second chance. Now, go provide that to somebody else."

**[12:30] Level 5, Life — codes 25, 26 (announced as "29"), 27** — **25. Design your environment around your behavior.** "Store things where you use them, not where they're supposedly meant to go. Keep the medicine near the coffee maker if you take it with breakfast. Put the book on your pillow if you want to read before bed." Embrace strategic duplication — "two chargers, two umbrellas, six pairs of reading glasses. Redundancy beats self-discipline." **[Announced as "Number 29" — evidently 26.] Spend money eliminating recurring misery before buying occasional pleasure.** "Fix the terrible mattress before booking the fancy weekend. Replace the shoes that hurt your feet. Buy the second monitor that makes every workday easier… The weekend in Antigua lasts three days. The mattress is every night of your year." **27. Create traditions on purpose.** "Sunday dinners, birthday breakfast, the same ridiculous photo every Thanksgiving. Rituals turn passing time into a life you can actually remember." His household makes "lucky pudding" every New Year's Day, a tradition begun "more than 20 years ago almost by accident" that "now has taken on the significance of a sacred religious right. Don't wait for traditions to form on their own. Build them."

**[13:46] Codes 28–30** — **28. Stop trying to be normal.** "Normal is crowded. Conformity is boring. Every interesting person I know is interesting precisely at the spots where they stopped asking, is this normal? and started asking, is this right for me? The parts of you that don't fit may be the parts most worth keeping." **29. Compete with yourself, not with somebody else.** "Social comparison is a rigged game. You're comparing their outsides with your insides, their carefully selected victory or curated profile with your entire chaotic, messy, unedited life." Change the opponent: "Was I better today than yesterday? Am I better at this than I was 6 months ago?… Don't aim for an Olympic medal in somebody else's event. Aim for a personal best." **30. Avoid unnecessary suffering, accept necessary suffering.** "Eliminate friction that proves nothing. Don't expect achievement, love, creativity, or a meaningful life to cost you nothing. Anything worthwhile will demand effort, discomfort, criticism, uncertainty, and sacrifice, lots of it. When you encounter those costs, don't automatically assume you're doing something wrong. You might simply be paying the price of admission."

**[15:07] Close — how to use the list** — His summary line: "Choose for Tuesdays, give friendship an infrastructure, get good at something others avoid, build traditions, and learn which difficulties to remove and which to accept." Then the instruction: **"cheat codes only work if you enter them. So, don't try all 30. Pick two. One that would remove hassle from your life, and one you've been resisting. Use both this week."**

Actionable: Run his own closing instruction rather than treating this as a reference list — pick one friction-remover and one resisted item for the week. Two codes map directly onto existing systems here: the waiting-for list (#17) covers what's owed on eBay buyer replies and client deliverables, which currently lives only in memory, and the recap email (#19) fits event and shoot bookings where terms get agreed verbally. Code #21 (real deadline vs stated deadline) is the one worth applying to client work immediately.

**Source**: [https://www.youtube.com/watch?v=c7jGXPEY54k](https://www.youtube.com/watch?v=c7jGXPEY54k)

**Hub**: [[mindset]]

**Tags**: #decision-making #relationships #productivity #work #life-design #cheat-codes #daniel-pink #gtd #deadlines #habits

**Date Added**: 2026-09-21

---

## Key Takeaways

[Add specific takeaways or connections to your work]

## Related Pages

- [[mindset-hub]]
